services:
  - type: web
    name: influencer-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node simple-backend.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: influencer-db
          property: connectionString

databases:
  - name: influencer-db
    region: singapore
    plan: free
    ipAllowList: []