services:
  - type: web
    name: influencer-marketing-backend
    env: node
    buildCommand: npm install
    startCommand: node simple-backend.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    healthCheckPath: /health